sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [3.10459, 1.744565, 1.82]
      rpy: ['-pi/2', 'pi/2', 0]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [4.9861935, 1.744565, 1.82]
      rpy: ['-pi/2', 'pi/2', 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [3.10459, -1.744565, 1.82]
      rpy: ['-pi/2', 'pi/2', 0]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [4.9861935, -1.744565, 1.82]
      rpy: ['-pi/2', 'pi/2', 0]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [0, 3.5, 1.82]
      rpy: ['-pi/2', 'pi/2', 0]

  # depth_camera_0:
  #   type: depth_camera
  #   pose:
  #     xyz: [3.082385, 1.750927, 1.82]
  #     rpy: [0, 'pi/2', 0]

  # logical_camera_0:
  #   type: logical_camera
  #   pose:
  #     xyz: [5, 1.750927, 1.82]
  #     rpy: [0, 'pi/2', 'pi/2']

  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [3.2, 3.64, 2.49]
      rpy: ['-pi/2', 'pi/2', 0]
  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [3.2, -3.64, 2.49]
      rpy: ['-pi/2', 'pi/2', 0]

  # logical_camera_6:
  #   type: logical_camera
  #   pose:
  #     xyz: [3.082385, 3.641234, 2.49]
  #     rpy: ['-pi/2', 'pi/2', 0]

  # depth_camera_1:
  #   type: depth_camera
  #   pose:
  #     xyz: [5, 3.641234, 2.49]
  #     rpy: [0, 'pi/2', 0]
  logical_camera_8:
    type: logical_camera
    pose:
      xyz: [-14.7, -3, 2.49]
      rpy: ['-pi/2', 'pi/2', 0]
  logical_camera_9:
    type: logical_camera
    pose:
      xyz: [-14.7, 3, 2.49]
      rpy: ['-pi/2', 'pi/2', 0]
  # laser_profiler_0:
  #   type: laser_profiler
  #   pose:
  #     xyz: [-17, -2, 1.526]
  #     rpy: [0, 0, 0]

  laser_profiler_0:
    type: laser_profiler
    pose:
      xyz: [-17, -4.4, 1.526]
      rpy: [0, 0, 0]

  # laser_profiler_1:
  #   type: laser_profiler
  #   pose:
  #     xyz: [-17, -2, 1.526]
  #     rpy: [0, 0, 0]

  # range_finder_0:
  #   type: proximity_sensor
  #   pose:
  #     xyz: [0, 2.84, 0.97]
  #     rpy: ['pi/2', 0.6, 'pi/2']

  # breakbeam_0:
  #   type: break_beam
  #   pose:
  #     xyz: [-0.26, 3.36, 0.94]
  #     rpy: [0, 0, 0]
